// messages
export const PUSH_MESSAGE = "PUSH_MESSAGE";
export const POP_MESSAGE = "POP_MESSAGE";

// map
export const SET_CENTER_MAP_LOCATION = "SET_CENTER_MAP_LOCATION";
export const SET_CURRENT_LOCATION_SUCCESS = "SET_CURRENT_LOCATION_SUCCESS";

// auth
export const UPDATE_USER = "UPDATE_USER";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const SEND_PASSWORD_RESET_EMAIL_SUCCESS =
  "SEND_PASSWORD_RESET_EMAIL_SUCCESS";
export const SEND_EMAIL_VERIFICATION_SUCCESS =
  "SEND_EMAIL_VERIFICATION_SUCCESS";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_ERROR = "UPDATE_PASSWORD_ERROR";
export const UPDATE_USER_PROFILE_PHOTO_URL_SUCCESS =
  "UPDATE_USER_PROFILE_PHOTO_URL_SUCCESS";
export const UPDATE_USER_PROFILE_PHOTO_URL_ERROR =
  "UPDATE_USER_PROFILE_PHOTO_URL_ERROR";
export const UPDATE_USER_PROFILE_PHOTO_URL_TEMP =
  "UPDATE_USER_PROFILE_PHOTO_URL_TEMP";

// profile
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

// listings
export const GET_LISTING_SUCCESS = "GET_LISTING_SUCCESS";
export const GET_LISTINGS_SUCCESS = "GET_LISTINGS_SUCCESS";
export const ADD_LISTING_SUCCESS = "ADD_LISTING_SUCCESS";
export const PUBLISH_LISTING_SUCCESS = "PUBLISH_LISTING_SUCCESS";
export const UPDATE_LISTING_SUCCESS = "UPDATE_LISTING_SUCCESS";
export const UPLOAD_LISTING_PHOTO_SUCCESS = "UPLOAD_LISTING_PHOTO_SUCCESS";
export const UPLOAD_LISTING_TEMP_PHOTO = "UPLOAD_LISTING_TEMP_PHOTO";

// brands
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS";
export const ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS";
export const PUBLISH_BRAND_SUCCESS = "PUBLISH_BRAND_SUCCESS";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPLOAD_BRAND_PHOTO_SUCCESS = "UPLOAD_BRAND_PHOTO_SUCCESS";
export const UPLOAD_BRAND_TEMP_PHOTO = "UPLOAD_BRAND_TEMP_PHOTO";

// reviews
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_ERROR = "ADD_REVIEW_ERROR";
